name: Bounty Watcher

on:
  schedule:
    - cron: '*/5 * * * *'  # ogni 5 minuti
  workflow_dispatch:  # ti permette di lanciarlo anche manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run bounty watcher
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python3 bounty_watcher.py
